// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqnnegrcqhloiuktaoat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhxbm5lZ3JjcWhsb2l1a3Rhb2F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0Mzc1NTQsImV4cCI6MjA2ODAxMzU1NH0.s4ZrUrRlwEucTIzxSz5axZGh44cltbZVG2vfqT3esyU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});